baseURL = 'https://r-insight.com/'
languageCode = 'en-us'
title = 'R-Insight'
disableHugoGeneratorInject = true
paginate = 15
pluralizeListTitles = false

[params]
    adsense-ad-client= 'ca-pub-XXXXXXXXXX'
    imageserver = 'https://i.imgur.com/'
    images = ["https://r-insight.com/img/gs5D7W9.png"]

[minify]
    minifyOutput = true

[taxonomies]
    author = 'authors'
    channel = 'channel'
    interest = 'interest'
    tag = 'tags'